### ISSUE TITLE
Question about Input

### ISSUE THREAD

**Issue by KevinMaroney** [yyoshiaki/VIRTUS#36]
Hi! Not so much an issue as 2 questions. I have some extremely high depth fastq files which were generated as paired end R1 R2, but for some reason when I merged my trimmed fastq's I didn't keep the original trimmed R1 or trimmed R2. When using "input.csv" should I indicate paired for the merged fastq input and it would still be able to deconvolute that? 

Also, I've tried using VirTect and the indexing step of human reference has taken 4 days. Does the initial setup for this take less time? Trying to get a simple analysis done on vacation for my PI who is frantically finishing up a grant on HSV and cancer. I've had a lot of trouble detecting viral reads in bulk and your pipeline seems simple, straightforward, and is exciting as a tool without the B.S. Thank you.

**Comment by yyoshiaki** [comment]
Do you mean that you have done the trimming yourself? VIRTUS includes trimming by fastp, so there is no need to trim by yourself. Also, you can specify either merged fastqs or individual fastqs in input.csv, since you can easily calculate the sum of multiple samples from the output.

As for the index, it is weird that it took 4 days. virTect itself is a combination of BWA, Bowtie, and other universal tools, so maybe the machine spec is too low or the machine was busy. VIRTUS index requires a machine with RAM >32Gb, but most machines can make the index within a few hours.

Finally, you should also take a look at the upgraded version of VIRTUS2. It is simpler.
https://github.com/yyoshiaki/VIRTUS2
